#!/usr/bin/env python3
# Copyright (c) 2026 Free Entropy formalization contributors.
# See LICENSE and NOTICE in the repository root for license and attribution.
"""Generate and verify a kernel-axiom audit of every public proof and definition."""
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent
ALLOWED = {"propext", "Classical.choice", "Quot.sound"}


def uncomment(text):
    result, i, depth = [], 0, 0
    while i < len(text):
        if text.startswith("/-", i):
            depth += 1
            i += 2
        elif depth and text.startswith("-/", i):
            depth -= 1
            i += 2
        elif depth:
            if text[i] == "\n":
                result.append("\n")
            i += 1
        elif text.startswith("--", i):
            j = text.find("\n", i)
            i = len(text) if j == -1 else j
        else:
            result.append(text[i])
            i += 1
    return "".join(result)


def declarations():
    items = []
    for path in sorted((ROOT / "FreeEntropy").glob("*.lean")):
        stack = []
        source = uncomment(path.read_text())
        if re.search(r"\b(sorry|admit|axiom)\b", source):
            raise SystemExit(f"FAILED: proof placeholder or axiom in {path}")
        for line in source.splitlines():
            scope = re.match(r"\s*(namespace|(?:noncomputable )?section)\s*(\S*)", line)
            if scope:
                stack.append((scope[1] == "namespace", scope[2]))
                continue
            if re.match(r"\s*end(?:\s|$)", line):
                if stack:
                    stack.pop()
                continue
            decl = re.match(
                r"\s*(?:@\[[^\]]*\]\s*)?(?:noncomputable\s+)?"
                r"(theorem|lemma|def|abbrev)\s+([^\s(:{]+)", line
            )
            if decl:
                prefix = ".".join(name for is_namespace, name in stack if is_namespace)
                items.append((decl[1], f"{prefix}.{decl[2]}" if prefix else decl[2]))
    return items


items = declarations()
# This is Lean's own #print-axioms collector, with the visited dependency
# set shared across declarations. The union is identical to the union of
# individual #print axioms results, while shared proofs are traversed once.
audit = "/-\nCopyright (c) 2026 Free Entropy formalization contributors.\n"
audit += "See LICENSE and NOTICE in the repository root for license and attribution.\n-/\n\n"
audit += "import FreeEntropy\nimport Lean.Util.CollectAxioms\n\n"
audit += "/- Generated by audit.py; all public proofs and definitions. -/\n\n"
audit += "open Lean in\nrun_cmd do\n  let names : Array Name := #[\n"
audit += ",\n".join(f"    `{name}" for _, name in items)
audit += "\n  ]\n  let env ← getEnv\n"
audit += "  for name in names do\n"
audit += "    unless (env.checked.get.find? name).isSome do\n"
audit += '      throwError "Missing kernel declaration: {name}"\n'
audit += "  let (_, result) := ((names.forM CollectAxioms.collect).run env).run {}\n"
audit += "  for name in names do\n"
audit += '    logInfo m!"\'{name}\' audited in the shared kernel dependency traversal"\n'
audit += '  logInfo m!"All audited declarations depend on axioms: {result.axioms}"\n'
# Retain ordinary per-declaration output for the final named theorem endpoints.
for _, name in items:
    if name in {
        "FreeEntropy.theorem1_achievability",
        "FreeEntropy.theorem1_converse",
        "FreeEntropy.theorem1_converse_of_uniform",
        "FreeEntropy.ExteriorRepresentation.theorem2_cloning_accuracy",
        "FreeEntropy.ExteriorRepresentation.theorem2_cartan_cloning_accuracy",
        "FreeEntropy.ExteriorRepresentation.theorem2_cloning_accuracy_petz",
        "FreeEntropy.ExteriorRepresentation.theorem2_cloning_accuracy_choi",
    }:
        audit += f"\n#print axioms {name}\n"
if sys.argv[1:] == ["--generate"]:
    (ROOT / "Audit.lean").write_text(audit)
    print(f"Generated audit for {len(items)} public declarations.")
else:
    if (ROOT / "Audit.lean").read_text() != audit:
        raise SystemExit("FAILED: audit is stale; regenerate and run Lean again")
    report = (ROOT / "verification/axioms.txt").read_text()
    if not re.search(r"All audited declarations depend on axioms:\s*\[", report):
        raise SystemExit("FAILED: combined kernel dependency traversal did not finish")
    if re.search(r"sorryAx|admitAx|error:", report):
        raise SystemExit("FAILED: placeholder or error in Lean axiom audit")
    for group in re.findall(r"depends? on axioms:\s*\[([^]]*)\]", report):
        unexpected = {a.strip() for a in group.split(",") if a.strip()} - ALLOWED
        if unexpected:
            raise SystemExit(f"FAILED: unexpected axioms {sorted(unexpected)}")
    for _, name in items:
        if f"'{name}'" not in report:
            raise SystemExit(f"FAILED: missing audit output for {name}")
    summary = {
        "status": "passed",
        "scope": "Complete Theorem 1 for actual known-spectrum physical tensor sources, all dimensions and positive ranks, with uniform achievability and Haar-average converse; complete Theorem 2 for the original Choi-projector channels, with proved Cartan and Petz identifications, signed dominant differences, rank one, and zero difference.",
        "lean_modules": len(list((ROOT / "FreeEntropy").glob("*.lean"))),
        "proof_sources_sha256": hashlib.sha256(b"".join(
            path.name.encode() + b"\0" + path.read_bytes()
            for path in sorted((ROOT / "FreeEntropy").glob("*.lean"))
        )).hexdigest(),
        "proved_declarations_audited": sum(kind in {"theorem", "lemma"} for kind, _ in items),
        "total_public_declarations_audited": len(items),
        "axiom_collection": "Lean.CollectAxioms.collect with a shared dependency traversal; final endpoints also checked with #print axioms",
        "lean_toolchain": (ROOT / "lean-toolchain").read_text().strip(),
        "mathlib_revision": "f156f7abd91ac67adb22bf999e5a71ba22e22e41",
        "allowed_axioms": sorted(ALLOWED),
        "manuscript_sha256": hashlib.sha256((ROOT.parent / "manuscript/article.tex").read_bytes()).hexdigest(),
    }
    (ROOT / "verification/summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(f"PASS: {len(items)} declarations; no placeholders or custom axioms.")
